//  vehcle type data
export const VEHCLETYPE_DATA_START = "VEHCLETYPE_DATA_START";
export const VEHCLETYPE_DATA_SUCCESS = "VEHCLETYPE_DATA_SUCCESS";
export const VEHCLETYPE_DATA_FAILURE = "VEHCLETYPE_DATA_FAILURE";

// vehcle id data

export const VEHCLE_ID_DATA_START = "VEHCLE_ID_DATA_START";
export const VEHCLE_ID_DATA_SUCCESS = "VEHCLE_ID_DATA_SUCCESS";
export const VEHCLE_ID_DATA_FAILURE = "VEHCLE_ID_DATA_FAILURE";

// Vehcle Bookig

export const VEHCLE_BOOKING_DATA_START = "VEHCLE_BOOKING_DATA_START";
export const VEHCLE_BOOKING_DATA_SUCCESS = "VEHCLE_BOOKING_DATA_SUCCESS";
export const VEHCLE_BOOKING_DATA_FAILURE = "VEHCLE_BOOKING_DATA_FAILURE";
